wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
