wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
