wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
hidden_sizes:
  value: 256,128,64,32
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
