wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: mnist
epochs:
  value: 15
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
