program: train.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  epochs:
    values: [5, 10]
  batch_size:
    values: [16, 32, 64]
  num_layers:
    values: [3, 4, 5]
  hidden_size:
    values: [32, 64, 128]
  learning_rate:
    values: [0.001, 0.0001]
  weight_decay:
    values: [0, 0.0005, 0.5]
  optimizer:
    values: ['sgd', 'momentum', 'nag', 'rmsprop', 'adam', 'nadam']
  weight_init:
    values: ['random', 'Xavier']
  activation:
    values: ['sigmoid', 'tanh', 'ReLU']
  loss:
    values: ['cross_entropy', 'mean_squared_error']
  dataset:
    value: 'fashion_mnist'