_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 32
dataset:
    value: fashion_mnist
epochs:
    value: 10
hidden_size:
    value: 32
learning_rate:
    value: 0.0001
loss:
    value: mean_squared_error
num_layers:
    value: 5
optimizer:
    value: momentum
weight_decay:
    value: 0.5
weight_init:
    value: Xavier
